name: Docker build and push PHP8.3

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    paths:
      - "8.3/**"
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set env to testing environment
        if: endsWith(github.ref, '/develop')
        run: |
          echo "IMAGE_TAG=devpanel/php-laravel:8.3-rc" >> $GITHUB_ENV

      - name: Set env to production environment
        if: endsWith(github.ref, '/main')
        run: |
          echo "IMAGE_TAG=devpanel/php-laravel:8.3" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./8.3/Dockerfile
          context: ./8.3
          push: true
          tags: ${{ env.IMAGE_TAG }}